---
- hosts: bluespice
  remote_user: root
  tasks:
  - name: Sicherstellen das libselinux-python installiert ist
    yum: name=libselinux-python state=latest
  - name: lokalen Hostseintrag machen
    lineinfile: path='/etc/hosts' state=present line='{{ ansible_default_ipv4.address }} {{ ansible_nodename }}' 
  - name: aktuelle Version von Apache installieren (falls noch nicht vorhanden)     
    yum: name=httpd state=latest 
 # - name: Apache-Konfiguration schreiben
 #   template: src=/root/index.html.j2 dest=/usr/share/httpd/noindex/index.html
 #   notify:
 #     - apache neustarten
  - name: Firewalld installieren
    yum: name=firewalld state=latest
  - name: Firewall ausschalten
    service: name=firewalld state=stopped
  - name: yum-utils installieren
    yum: name=yum-utils state=latest
  - name: PHP-7 Repo installieren
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present
  #- name: PHP-Module installieren
  #  yum: name=php-curl,php-gd,php-tidy,yum-utils state=latest
  - name: php72 Repo aktivieren
    command: yum-config-manager --enable remi-php71
  - name: PHP-7.1 Module installieren
    yum: name=php71,php71-php,php71-php-gd,php71-php-xml,php71-php-curl,php71-php-tidy,php71-php-mbstring,php71-php-intl,php71-php-pdo,php71-php-pecl-mysql,php,php-mbstring,php-xml,php-mysql,php-gd,php-intl state=latest
  - name: Mariadb installieren
    yum: name=mariadb-server state=latest
  - name: MariaDB starten
    service: name=mariadb state=started
  - name: Passwort für root-Benutzer von mariadb setzen
    command: mysqladmin -uroot password Seminar2017
  - name: Datenbank "my_wiki" erstellen
    command: mysqladmin -u root -pSeminar2017 create my_wiki
  - name: Bluespice mit Mediawiki herunterladen
    get_url: url=https://sourceforge.net/projects/bluespice/files/BlueSpice-free-2.27.2-installer.zip/download dest=/root
  - name: Bluespice entpacken
    unarchive: src=/root/BlueSpice-free-2.27.2-installer.zip dest=/root remote_src=True
  - name: Webinhalte von /var/www/html löschen
    command: rm -rf /var/www/html
  - name: Webinhalte nach /var/www/html verschieben
    command: mv /root/bluespice-free-installer /var/www/html
  - name: Besitzer für Verzeichnis auf apache stellen
    command: chown -R apache:apache /var/www/html
  - name: Lese und Schreibrechte für Verzeichnisse setzen
    file:
      path: /var/www/html
      mode: u=rwX,g=rwX,o=rX
      owner: apache
      group: apache
      recurse: yes
  - name: Data umbenennen
    command: mv /var/www/html/extensions/BlueSpiceFoundation/data.template /var/www/html/extensions/BlueSpiceFoundation/data
  - name: Config umbenennen
    command: mv /var/www/html/extensions/BlueSpiceFoundation/config.template /var/www/html/extensions/BlueSpiceFoundation/config
  - name: LocalSettings schreiben
    template: src=/etc/ansible/LocalSettings.php.j2 dest=/var/www/html/LocalSettings.php
    notify:
      - apache neustarten
  - name: Paket installieren 
    yum: state=latest name=MySQL-python 
  - lineinfile: 
      path: /etc/hosts 
      state: present 
      line: '{{ ansible_default_ipv4.address }} {{ ansible_nodename }}' 
  - name: MySQL Dump einlesen
    mysql_db: state=import login_user=root login_password=Seminar2017 name="my_wiki" target=/var/www/html/maintenance/tables.sql
  - name: Install.php aufrufen
    command: php /var/www/html/maintenance/install.php --conf /var/www/html/LocalSettings.php --scriptpath "" --pass Seminar2017 SCNWiki administrator
    failed_when: result.rc not in [0,1]
    register: result
  - name: PHP Updateskript ausführen
    command: php /var/www/html/maintenance/update.php
    failed_when: result.rc not in [0,1]
    register: result
  - name: Benutzer Admin mit Passwort Seminar2017 als System Operator erstellen
    command: php /var/www/html/maintenance/createAndPromote.php --sysop admin Seminar2017
    notify:
      - apache neustarten
  handlers:
     - name: apache neustarten
       service: name=httpd state=restarted

