---
- hosts: mynode1
  vars:
   webservername: testname
  tasks:
  - name: Pfadstats ziehen
    stat: path=/root/{{webservername}}
    register: p
  - debug:
       msg: "Path exists and is a directory"
    when: p.stat.isdir is defined and p.stat.isdir
