---
- hosts: testsystem
  vars:
  - logicalvolume: lvhome
  - volumegroup: "{{ ansible_lvm['lvs'][logicalvolume]['vg']}}"
  tasks:
  - name: Ausgabe der genutzten Volumegruppe und logischen Volumes
    debug: msg="Erweitere Volume {{ logicalvolume }} von VG {{ volumegroup  }} um 10% des freien Platzes"
  - name: Erweitern des logischen Volumes, um 30% des freien VG-Speicherplatzes
    lvol:
      vg: "{{ volumegroup}}"
      lv: "{{ logicalvolume }}"
      size: +10%FREE
  - name: Dateisystem ebenfalls erweitern via resize2fs
    command: resize2fs /dev/mapper/{{ volumegroup }}-{{ logicalvolume }}    

